apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-world
  labels:
    app: hello-world
spec:
  replicas: 3 # Wir starten direkt mit 3 Kopien für Hochverfügbarkeit! 👯‍♂️
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Erstellt in der Cloud automatisch einen externen Load Balancer 🚦
