version: '3.8'

services:
  # Tier 3: Data - Die PostgreSQL Datenbank
  db:
    image: postgres:15-alpine
    container_name: postgres_db_local
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperSecurePassword123
      POSTGRES_USER: postgres
      POSTGRES_DB: cloud_basics_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Tier 2: Logic - pgAdmin (Weboberfläche zur Verwaltung)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgAdminPassword123
      # Wir lassen pgAdmin auf Port 80 im Container laufen (Standard)
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
